name: Add needs-triage
on:
  issues:
    types: [opened, reopened]
jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add labels to new issue
        run: |
          gh issue edit ${{ github.event.issue.number }} --add-label "needs-triage"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}